### PR TITLE
[0.5] Add admin actions

### LINKED ISSUE #650: Admin actions to correct state in EOS EVM
Issues can arise due to bugs within the EOS EVM Contract that causes it to deviate from the intended behavior of the EVM protocol. This can lead to the state in the contract deviating from what it should be (and also deviating from what it is in the EOS EVM Node). 

These deviations are possible without the EOS EVM Node necessarily failing to replay the virtual blockchain constructed from the transactions processed by EOS EVM Contract and committed within the EOS blockchain. In such a case, the easiest path to correcting the deviation is to simply correct to state to what it should be.

So, this issue tracks an enhancement to EOS EVM Contract which adds a set of new administrative actions (only callable by the same authority that can already update the EOS EVM Contract code) to modify the state in particular ways.

Three new actions are needed to modify the subset of contract state which impacts EVM state (i.e. is also replicated in EOS EVM Node):

1. `setkvstore`: Set (upsert) or remove key-value storage slots from a specified account's storage. The account should be specified by its implementation-specific account ID.
2. `rmaccount`: Remove an account (referenced by its implementation-specific account ID) and add it to the `gcstore` table so that later garbage collection processing can clean up any storage slots it leaves behind. Note: reference counts of any code attached to the account must be updated, and if the reference count reaches zero, the code should also be removed from the tables.
3. `addevmbal`: Add a positive or negative delta to the balance stored in an EVM account. The account should be specified by its implementation-specific account ID. The invariant that the `inevm` table tracks the total sum of all EVM account balances should continue to be maintained (under the assumption that that the invariant was already true prior to the `addevmbal` action call).

Furthermore, three additional actions are needed to modify other parts of the contract state:
1. `addopenbal`: Add a positive or negative delta to the balance stored within the EOS EVM Contract on the EOS side associated with an EOS account that opened a balance in the contract. The account should be specified using the EOS account name.
2. `rmgcstore`: Remove an entry from the `gcstore` table. The entry should be specified by the primary key ID of the table row to be removed.
3. `freezeaccnt`: Modify a flag associated with an EVM account (specified by the implementation-specific account ID) to put it into or take it out of a freeze state. When an EVM account is in the freeze state, no interactions with it are possible. The user cannot sign a transaction for that account. A contract at that account cannot be called. It should not even be possible to send value to the frozen account.

### PR DESCRIPTION
**Pull request by elmato**
Resolve #650

### CODE REVIEW

File: contract/tests/basic_evm_tester.cpp [hunk 1]
```diff
@@ -513,4 +572,73 @@ bool basic_evm_tester::scan_account_storage(uint64_t account_id, std::function<b
...
+
+   scan_table<account_code>(
+      account_code_table_name, evm_account_name, [&visitor](account_code&& row) { return visitor(row); }
+   );
+
+   return true;
+}
+
+//TODO: remove when merging
+//---begin
```
Comment (arhag) [inline contract/tests/basic_evm_tester.cpp:598]: Remove these two comments.

File: contract/tests/basic_evm_tester.cpp [hunk 2]
```diff
@@ -513,4 +572,73 @@ bool basic_evm_tester::scan_account_storage(uint64_t account_id, std::function<b
...
+      return false;
+   });
+
+   auto evm_eos_balance = intx::uint256(balance_and_dust{.balance=get_eos_balance(evm_account_name), .dust=0});
+   if(evm_eos_balance != total_in_accounts+total_in_evm_accounts) {
+      dlog("evm_eos_balance: ${evm_eos_balance}, total_in_accounts+total_in_evm_accounts: ${tt}",("tt",intx::to_string(total_in_accounts+total_in_evm_accounts))("evm_eos_balance",intx::to_string(evm_eos_balance)));
+      throw std::runtime_error("evm_eos_balance != total_in_accounts+total_in_evm_accounts");
+   }
+}
+//---end
```
Comment (arhag) [inline contract/tests/basic_evm_tester.cpp:642]: Remove this comment.

File: contract/tests/basic_evm_tester.hpp [hunk 3]
```diff
@@ -252,6 +286,17 @@ class basic_evm_tester : public testing::validating_tester
    std::optional<account_object> find_account_by_address(const evmc::address& address) const;
    std::optional<account_object> find_account_by_id(uint64_t id) const;
    bool scan_account_storage(uint64_t account_id, std::function<bool(storage_slot)> visitor) const;
+   bool scan_gcstore(std::function<bool(gcstore)> visitor) const;
+   bool scan_account_code(std::function<bool(account_code)> visitor) const;
+
+   //TODO: remove before merge
+   //---begin
```
Comment (arhag) [inline contract/tests/basic_evm_tester.hpp:293]: Remove these two comments.

File: contract/tests/basic_evm_tester.hpp [hunk 4]
```diff
@@ -252,6 +286,17 @@ class basic_evm_tester : public testing::validating_tester
...
+   balance_and_dust inevm() const;
+   asset get_eos_balance( const account_name& act );
+   void scan_balances(std::function<bool(evm_test::vault_balance_row)> visitor) const;
+   void check_balances();
+   //---end
```
Comment (arhag) [inline contract/tests/basic_evm_tester.hpp:298]: Remove this comment.

File: contract/tests/basic_evm_tester.cpp [hunk 5]
```diff
@@ -55,8 +57,24 @@ struct storage_table_row
 
 } // namespace evm_test
 
+namespace fc { namespace raw {
+    template<>
+    inline void unpack( datastream<const char*>& ds, evm_test::partial_account_table_row& tmp)
+    { try  {
+      dlog("enrtro en partial_account_table_row unpack");
```
Comment (arhag) [inline contract/tests/basic_evm_tester.cpp:64]: Can we remove this dlog statement now?

**Review by arhag — CHANGES_REQUESTED** [review]

**Review by arhag — APPROVED** [review]
